version: "3"

services: 
    avaliativo  :
        build:  
            context: .
            dockerfile: Dockerfile
        ports: 
            - 3000:3002
        command: npm start
        volumes: 
            - .:/app