version: "3"

services: 
    avaliativo  :
        build:  
            context: .
            dockerfile: Dockerfile
        ports: 
            - 3001:3001
        command: npm start --port=3001
        volumes: 
            - .:/app